### ISSUE TITLE
no highlighting for nextclick

### ISSUE THREAD

**Issue by nileio** [Smart-Harvesting/language-oxpath#11]
thanks for posting this code.
i notice there is no highlighting for nextclick action.

Thanks
Sam

**Comment by neumannm** [comment]
Hi Sam, well actually there should be, because I fixed this with the last update. Could you please check if you are using v0.3.1 of the language package?

**Comment by nileio** [comment]
Oh yes. I did'nt realise there is an update.. I updated and highlighting is there now.
Thanks!

**Comment by neumannm** [comment]
Sure, no problem. I'm glad it worked for you. Thanks for submitting the issue anyway.
